### PR TITLE
Firefox 51 (w/Marionette enabled)

### PR DESCRIPTION
**Pull request by stephendonner**
WIP - can't get this to run locally, but it passes the ad-hoc build:

http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/fxapom.adhoc/79/

This is and will break in Python 3.5 environments, too; and I think there's probably more work I need to do with setup.py and tox, etc.

@davehunt thoughts?

### CODE REVIEW

**Comment by davehunt** [comment]
It's also failing in Travis because geckodriver is not installed. Is it important that we upgrade to Firefox 51? If not, I would hold off until geckodriver is closer to WebDriver compliant, at which point this upgrade should be much less painful.

**Comment by stephendonner** [comment]
Yeah, it's not worth the effort right now (at least for me) and if/since you feel the same, I'm happy to close and revisit this!

**Comment by jrbenny35** [comment]
My addons-test move to addons server uses Marionette (not sure of the version),. Until the recent geckodriver release I had to use Firefox 47.0.2, as I would get POST errors and hover action errors. Updating to geckodriver 15 and using firefox 55, has solved those. I don't know if that's worth a shot.

**Comment by davehunt** [comment]
> My addons-test move to addons server uses Marionette (not sure of the version),. Until the recent geckodriver release I had to use Firefox 47.0.2, as I would get POST errors and hover action errors. Updating to geckodriver 15 and using firefox 55, has solved those. I don't know if that's worth a shot.

Marionette doesn't really have a version number, as it's built into Firefox. The latest version of geckodriver and Firefox does indeed support actions, however pointer actions didn't make it into Firefox 52. As we run these tests on Sauce Labs we can't rely on nightly Firefox builds. I'd also hold off on migrating to geckodriver and Marionette until the wait for page load after click is fixed.

**Pull request closed without merging**
