### PR TITLE
Try removing old sudo: required for Travis

### PR DESCRIPTION
**Pull request by stephendonner**

### CODE REVIEW

**Comment by stephendonner** [comment]
From https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System - claims it should help with boot time.

@davehunt thoughts?

**Comment by davehunt** [comment]
16:37 davehunt: stephend: hmm.. sudo used to be a requirement for using Docker in Jenkins
16:38 davehunt: stephend: https://docs.travis-ci.com/user/docker/
16:38 davehunt: "Travis CI automatically routes builds to run on Trusty sudo: required when services: docker is configured. We do not currently support use of Docker on OS X."
16:39 davehunt: stephend: I suspect your change is being ignored, as sudo is clearly being used in the build

**Comment by stephendonner** [comment]
@davehunt so close, or rework?

**Comment by davehunt** [comment]
Well as I understand it, sudo is required. If so, what does this solve for us? I am perhaps not understanding the motivation behind the pull request.

**Comment by stephendonner** [comment]
I believe I've mistaken/misunderstood a couple things, so closing; thanks!

**Pull request closed without merging**
