### PR TITLE
Switch Dockerfile image to Ubuntu, from Alpine

### PR DESCRIPTION
**Pull request by stephendonner**
@davehunt thoughts/r?

While I'm not 100% sure you/we want this, I thought of doing this a while back, when we converted a few test suites (Mozillians, Socorro) to use Ubuntu over Alpine, and then decided to try for it, when I saw https://travis-ci.org/mozilla/fxapom/jobs/347891735#L483-L508

Built and ran locally, with all tests passing in both Python 2.7 and 3.6.

Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/fxapom.adhoc/214/

### CODE REVIEW

**Comment by stephendonner** [comment]
xref: https://github.com/mozilla/fxapom/issues/204

**Comment by jrbenny35** [comment]
What was the idea behind using alpine?

**Comment by davehunt** [comment]
> What was the idea behind using alpine?

Economy. It's a much smaller base image, so should be faster for CI/users to build.

Thanks for this @stephendonner. It was great that we got Alpine to work, but it seems too unstable for our needs.

**Comment by stephendonner** [comment]
NP; while I learned a lot, and was eventually able to get the base image building again, it still didn't run right, after I did -- too much wrangling!

Fixed by https://github.com/mozilla/fxapom/commit/aa0fa5f004875c666c0db91fe1084d15333c51cc

**Pull request merged**
