### PR TITLE
Update PyFxA to 0.1.1

### PR DESCRIPTION
**Pull request by stephendonner**
Would love for someone to double-check this, but I:
1) tested locally, and all passes except for one test - tests/marionette/test_fxa_login.py E (http://pastebin.com/ewZPQM7b)
2) passes the adhoc job on staging Jenkins, here: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/fxapom.adhoc/34/console (https://pastebin.mozilla.org/8864132)

@davehunt @bobsilverberg @mozilla/web-qa-sorcerers r?

### CODE REVIEW

**Comment by davehunt** [comment]
The Marionette test that's failing locally is most likely because you don't have Firefox installed in the default path for the suite. Try adding `--bin /path/to/firefox-bin` to your command line. This has my r+ and Travis is happy with it (including the Marionette test) so I'm happy to merge, but I'll hold off to let you experiment with getting the Marionette test running locally. Also, this branch is apparently out-of-date with the master branch, so you may need to rebase and pull from upstream.

**Comment by davehunt** [comment]
We should also bump the fxapom version number and release to PyPI once this has landed.

**Comment by stephendonner** [comment]
Sorry @davehunt - I forgot about this, and also bungled it :-(

1) I deleted the branch, stupidly, but have re-pushed since my local changes are still here, in-tact
2) Even with what appears to be the right path to Firefox (because it autocompletes for me, and the error definitely looks like it tries to open it, file-system wise), I still get errors.

https://pastebin.mozilla.org/8865072

**Comment by stephendonner** [comment]
The changes are still in https://github.com/stephendonner/fxapom/tree/pyfxa so maybe this is salvageable with a bit of Git magic?

**Comment by davehunt** [comment]
> 2) Even with what appears to be the right path to Firefox (because it autocompletes for me, and the error definitely looks like it tries to open it, file-system wise), I still get errors.

I don't think `--bin /../../../Applications/Firefox.app/` is enough as it's expecting the binary. Try `--bin /../../../Applications/Firefox.app/Contents/MacOS/firefox-bin`

> The changes are still in https://github.com/stephendonner/fxapom/tree/pyfxa so maybe this is salvageable with a bit of Git magic?

You should be able to pull this locally and push again, but I'm not sure if GitHub will recover as it currently states 'unknown repository' so you may need to open a new pull request.

**Comment by stephendonner** [comment]
Figured this out (thanks again Bob and @davehunt ) and have submitted a new pull: https://github.com/mozilla/fxapom/pull/27

**Pull request closed without merging**
