### PR TITLE
Upgrade to Firefox 53.0

### PR DESCRIPTION
**Pull request by stephendonner**
@davehunt r?

Ad-hoc here: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/fxapom.adhoc/84/console

### CODE REVIEW

**Comment by stephendonner** [comment]
Actually, I'm not sure it's a good idea for me to leave Firefox at version 52.0.2 in Travis CI, while Sauce-Labs run tests are using 53.0.  Thoughts?

I couldn't get Travis CI and 53.0 to work: got the following error on some tests[0]:

```WebDriverException: Message: Missing 'marionetteProtocol' field in handshake```

[0] https://travis-ci.org/mozilla/fxapom/jobs/228490122

**Comment by jrbenny35** [comment]
I think you need to update selenium but I don't see where you actually install selenium. The requirements file doesn't have it.

**Comment by davehunt** [comment]
> I think you need to update selenium but I don't see where you actually install selenium. The requirements file doesn't have it.

The console shows the latest version of Selenium was in use (3.4.1). We don't tend to pin Selenium, however I'm not against doing so now we have pyup.io to manage dependencies.

The issue here is that you're running the tests against Firefox 38.4.0. This is because the attempt to download from https://download.mozilla.org/?product=firefox-53&lang=en-US&os=linux64 returned a 404. Try setting version to 53.0.

**Comment by davehunt** [comment]
Ah, I see this is already resolved. I'll review it then.

**Pull request merged**
