### PR TITLE
Switch to Firefox 52 w/Marionette

### PR DESCRIPTION
**Pull request by stephendonner**
@davehunt r?

Passing ad-hocs are https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/fxapom.adhoc/73/ - https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/fxapom.adhoc/77/

### CODE REVIEW

**Comment by jrbenny35** [comment]
Also for your travis tests to pass you'll need to install geckodriver.

**Comment by stephendonner** [comment]
@jrbenny35 lame answer on my part: because I saw it in https://github.com/mozilla/mozillians-tests/commit/9d477dc39b2997f6af60e27435d184acfaca0ed8#diff-484462fced51d1a06b1d93b4a44dd535R19

And, I really don't know this code well at all (it shows!)  Looks like I've got to deal with the new "tags" not-being-recognized-as-a-valid-WebDriver-thing failure, which comes from here: https://github.com/stephendonner/fxapom/blob/4c7740ff3f3ed7a7386925b320343d7ba0a7d303/tests/conftest.py#L14

Sorry, @davehunt - perhaps this is better as a brief hack session?

**Comment by jrbenny35** [comment]
Ah no worries. With pytest-selenium you don't have to check the browser name to use marionette. It will automatically call the capabilities fixture if the driver is Firefox.

**Comment by davehunt** [comment]
> Ah no worries. With pytest-selenium you don't have to check the browser name to use marionette. It will automatically call the capabilities fixture if the driver is Firefox.

It's still a good idea to check the browser name. If the tests are being run against Chrome (for example), then you don't want to set the marionette capability. Note that this isn't the case for suites that will only ever run against Firefox.

> I really don't know this code well at all (it shows!) Looks like I've got to deal with the new "tags" not-being-recognized-as-a-valid-WebDriver-thing failure

Yep, this is something I hit recently. Sauce Labs either need to start using a prefix for their capabilities, or we need to only add these capabilities if we know we're using Sauce Labs. This is how I solved it for a local suite:

```python
@pytest.fixture(scope='session')
def session_capabilities(pytestconfig, session_capabilities):
    if pytestconfig.getoption('driver') == 'SauceLabs':
        session_capabilities.setdefault('tags', []).append('treeherder')
    return session_capabilities
```

**Comment by stephendonner** [comment]
@davehunt I think this is ready for a hopefully-final r?  Maybe we won't need that hack session, after all :)

**Pull request merged**
