### PR TITLE
Remove PyFxA from requirements.txt and move that file into tests/

### PR DESCRIPTION
**Pull request by bobsilverberg**

### CODE REVIEW

**Comment by bobsilverberg** [comment]
We will also need to make sure that `setup.py` is now run prior to running the tests, and that the requirements file is loaded from `tests/`.

**Comment by bobsilverberg** [comment]
Adhoc seems happy at http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/fxapom.adhoc/7/

@davehunt r?

**Comment by davehunt** [comment]
r+

**Comment by bobsilverberg** [comment]
Thanks @davehunt!

**Pull request merged**
